name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Print date
        run: |
          date
      - name: Print current directory
        run: |
          ls -l
      - name: commits
        if: ${{ contains(github.event.commits.*.message, '#skip') }}
